server:
  port: 8050
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/students_db
    username: studentadmin
    password: studentadminpass
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update # validate
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    baseline-on-migrate: true
    validate-on-migrate: False
    enabled: true
    baseline-description: "init"
    baseline-version: 0
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
