server:
  port: 9898
spring:
  servlet:
    multipart:
      max-file-size: 50MB
  datasource:
    url: jdbc:postgresql://localhost:5433/auth_db
    username: authadmin
    password: authpassword
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update # validate
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    baseline-on-migrate: true
    validate-on-migrate: false
    enabled: true
    baseline-description: "init"
    baseline-version: 0
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
#  mail:
#    host: localhost
#    port: 1023
#    username: admin
#    password: admin
#    properties:
#      mail:
#        smtp:
#          trust: "*"
#        auth: true
#        starttls:
#          enabled: true
#        connectiontimeout: 5000
#        timeout: 3000
#        writetimeout: 5000
  application:
    name: AUTH-SERVICE
application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 864000
  mailing:
    frontend:
      activation-url: http://localhost:4200/activate-account